server:
  port: 9007

bk:
  nacos:
    server-addr: ${NACOS_SERVER:127.0.0.1:8080}
    namespace: ${NACOS_NAMESPACE:1bde955a-3394-4f3e-a754-70e0aee942dd}

spring:
  application:
    name: media-worker-service
  config:
    import: nacos:${spring.application.name}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: ${bk.nacos.server-addr}
        namespace: ${bk.nacos.namespace}
      config:
        server-addr: ${bk.nacos.server-addr}
        namespace: ${bk.nacos.namespace}
        file-extension: yaml

dubbo:
  application:
    name: media-worker-service
    qos-enable: true                  # 开启QoS（默认true）
    qos-port: 22519                   # 独立端口，避免与默认22222冲突
  protocol:
    name: dubbo
    port: 20887
  registry:
    address: nacos://${bk.nacos.server-addr}?namespace=${bk.nacos.namespace}
