package com.bkanent.agent.model.planner;

import java.util.List;

/**
 * Planner definition generated by the model.
 */
public record AgentPlan(
        String objective,
        String summary,
        List<AgentPlanStep> steps
) {
}
