package com.bkanent.settlement.service.impl;

import com.bkanent.common.agent.AgentCard;
import com.bkanent.common.agent.AgentTaskInvokeRequest;
import com.bkanent.common.agent.AgentTaskInvokeResponse;
import com.bkanent.settlement.model.SettlementCalculateRequest;
import com.bkanent.settlement.model.SettlementDetailResponse;
import com.bkanent.settlement.model.SettlementMonthlySummaryResponse;
import com.bkanent.settlement.service.SettlementAgentService;
import com.bkanent.settlement.service.SettlementManagementService;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

import java.math.BigDecimal;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
public class SettlementAgentServiceImpl implements SettlementAgentService {

    private final SettlementManagementService settlementManagementService;

    public SettlementAgentServiceImpl(SettlementManagementService settlementManagementService) {
        this.settlementManagementService = settlementManagementService;
    }

    @Override
    public AgentCard getAgentCard() {
        return new AgentCard(
                "settlement-agent",
                "Settlement Agent",
                "Responsible for settlement calculation, payout preparation and monthly summary analysis",
                "1.0.0",
                List.of("settlement-calculate", "settlement-payout-prepare"),
                List.of("settlement"),
                true,
                true,
                "/a2a",
                List.of("text", "json"),
                List.of("text", "json")
        );
    }

    @Override
    public AgentTaskInvokeResponse invoke(AgentTaskInvokeRequest request) {
        Map<String, Object> context = request.structuredContext() == null ? Map.of() : request.structuredContext();
        SettlementDetailResponse detail = resolveDetail(context);
        List<SettlementMonthlySummaryResponse> monthlySummary = resolveMonthlySummary(context);

        Map<String, Object> output = new LinkedHashMap<>();
        output.put("resultType", "settlement_prepare");
        output.put("contentType", "settlement_summary");
        output.put("artifactTypeHint", "settlement_detail_body");
        output.put("settlementStatus", detail == null ? "PREPARED" : detail.payoutStatus());
        output.put("summary", buildSummary(detail, monthlySummary));
        output.put("detail", detail == null ? Map.of() : Map.of(
                "settlementId", detail.id(),
                "contractId", detail.contractId(),
                "statMonth", detail.statMonth(),
                "commissionAmount", detail.commissionAmount(),
                "payoutStatus", detail.payoutStatus()
        ));
        output.put("monthlySummary", monthlySummary.stream().map(item -> Map.of(
                "summaryScope", item.summaryScope(),
                "statMonth", item.statMonth(),
                "dealCount", item.dealCount(),
                "totalCommissionAmount", item.totalCommissionAmount(),
                "payoutStatus", item.payoutStatus()
        )).toList());
        output.put("nextAction", resolveNextAction(detail, context));

        return new AgentTaskInvokeResponse(
                request.sessionId(),
                request.taskId(),
                "settlement-agent",
                "COMPLETED",
                output,
                List.of(),
                List.of("settlement.batch", "notification.send"),
                String.valueOf(output.get("summary")),
                request.traceId()
        );
    }

    private SettlementDetailResponse resolveDetail(Map<String, Object> context) {
        Long settlementId = asLong(context.get("settlementId"));
        if (settlementId != null) {
            return settlementManagementService.getSettlementDetail(settlementId);
        }
        if (context.containsKey("dealAmount")) {
            return settlementManagementService.calculateSettlement(new SettlementCalculateRequest(
                    asLong(context.get("employeeId")),
                    text(context.get("employeeName"), "待结算员工"),
                    text(context.get("teamName"), null),
                    text(context.get("storeName"), null),
                    asLong(context.get("contractId")),
                    asLong(context.get("listingId")),
                    text(context.get("contractType"), "SECOND_HAND"),
                    text(context.get("statMonth"), "2026-05"),
                    asDecimal(context.get("dealAmount"), BigDecimal.ZERO),
                    asDecimal(context.get("commissionRate"), null),
                    asDecimal(context.get("storeSplitRatio"), null),
                    asDecimal(context.get("teamSplitRatio"), null),
                    text(context.get("ruleCode"), null),
                    "Generated by settlement-agent"
            ));
        }
        return null;
    }

    private List<SettlementMonthlySummaryResponse> resolveMonthlySummary(Map<String, Object> context) {
        String month = text(context.get("statMonth"), text(context.get("month"), null));
        if (!StringUtils.hasText(month)) {
            return List.of();
        }
        return settlementManagementService.summarizeMonthlyCommission(month, text(context.get("summaryScope"), null));
    }

    private String buildSummary(SettlementDetailResponse detail, List<SettlementMonthlySummaryResponse> monthlySummary) {
        if (detail != null) {
            return "Settlement prepared for contract " + detail.contractId() + ", payout status " + detail.payoutStatus();
        }
        if (!monthlySummary.isEmpty()) {
            SettlementMonthlySummaryResponse first = monthlySummary.get(0);
            return "Settlement monthly summary ready for " + first.statMonth() + ", payout status " + first.payoutStatus();
        }
        return "Settlement preparation finished with contextual estimate.";
    }

    private String resolveNextAction(SettlementDetailResponse detail, Map<String, Object> context) {
        if (detail != null && !"PAID".equalsIgnoreCase(detail.payoutStatus())) {
            return "prepare_payout_batch";
        }
        if (Boolean.TRUE.equals(context.get("requireNotification"))) {
            return "notify_stakeholders";
        }
        return "settlement_ready";
    }

    private Long asLong(Object value) {
        if (value instanceof Number number) {
            return number.longValue();
        }
        if (value instanceof String text && !text.isBlank()) {
            try {
                return Long.parseLong(text);
            } catch (NumberFormatException ignored) {
                return null;
            }
        }
        return null;
    }

    private BigDecimal asDecimal(Object value, BigDecimal defaultValue) {
        if (value instanceof BigDecimal decimal) {
            return decimal;
        }
        if (value instanceof Number number) {
            return BigDecimal.valueOf(number.doubleValue());
        }
        if (value instanceof String text && !text.isBlank()) {
            try {
                return new BigDecimal(text);
            } catch (NumberFormatException ignored) {
                return defaultValue;
            }
        }
        return defaultValue;
    }

    private String text(Object value, String defaultValue) {
        if (value == null) {
            return defaultValue;
        }
        String text = String.valueOf(value);
        return text.isBlank() ? defaultValue : text;
    }
}
