package com.bkanent.settlement.mcp;

import com.bkanent.common.tool.McpTool;
import com.bkanent.settlement.model.SettlementCalculateRequest;
import com.bkanent.settlement.model.SettlementDetailResponse;
import com.bkanent.settlement.model.SettlementMonthlySummaryResponse;
import com.bkanent.settlement.model.SettlementPayoutBatchResponse;
import com.bkanent.settlement.service.SettlementManagementService;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.List;

@Component
public class SettlementMcpTools implements McpTool {

    private final SettlementManagementService settlementManagementService;

    public SettlementMcpTools(SettlementManagementService settlementManagementService) {
        this.settlementManagementService = settlementManagementService;
    }

    @Tool(description = "Get the full detail of a settlement by its ID, including commission amount, payout status, and split records.")
    public SettlementDetailResponse getSettlementDetail(
            @ToolParam(description = "Settlement ID") Long settlementId) {
        return settlementManagementService.getSettlementDetail(settlementId);
    }

    @Tool(description = "Calculate settlement commission for a deal. Returns the settlement detail with commission amount and split records.")
    public SettlementDetailResponse calculateSettlement(
            @ToolParam(description = "Employee ID") Long employeeId,
            @ToolParam(description = "Contract ID") Long contractId,
            @ToolParam(description = "Listing ID") Long listingId,
            @ToolParam(description = "Deal amount in yuan") BigDecimal dealAmount,
            @ToolParam(description = "Stat month in yyyy-MM format, e.g. 2026-05") String statMonth) {
        return settlementManagementService.calculateSettlement(new SettlementCalculateRequest(
                employeeId, null, null, null, contractId, listingId,
                "SECOND_HAND", statMonth, dealAmount, null, null, null, null,
                "Generated by settlement-agent"));
    }

    @Tool(description = "Get monthly commission summary for a given month. Returns aggregated commission data grouped by scope (store/team/personal).")
    public List<SettlementMonthlySummaryResponse> getMonthlySummary(
            @ToolParam(description = "Month in yyyy-MM format") String month,
            @ToolParam(description = "Summary scope: STORE, TEAM, PERSONAL. Pass empty string for all.") String summaryScope) {
        return settlementManagementService.summarizeMonthlyCommission(month,
                summaryScope == null || summaryScope.isBlank() ? null : summaryScope);
    }

    @Tool(description = "Create a payout batch for a given month. Collects all unsettled records and groups them into a payout batch.")
    public SettlementPayoutBatchResponse createPayoutBatch(
            @ToolParam(description = "Month in yyyy-MM format") String month) {
        return settlementManagementService.createPayoutBatch(month);
    }
}
