server:
  port: 9002

bk:
  nacos:
    server-addr: ${NACOS_SERVER:127.0.0.1:8848}
    namespace: ${NACOS_NAMESPACE:791847cb-c957-4f7b-81d4-3e5bcbc8620c}

spring:
  application:
    name: agent-service
  config:
    import: nacos:${spring.application.name}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: ${bk.nacos.server-addr}
        namespace: ${bk.nacos.namespace}
      config:
        server-addr: ${bk.nacos.server-addr}
        namespace: ${bk.nacos.namespace}
        file-extension: yaml

dubbo:
  application:
    name: agent-service
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: nacos://${bk.nacos.server-addr}?namespace=${bk.nacos.namespace}
