server:
  port: 9013

spring:
  application:
    name: settlement-service
  config:
    import: optional:nacos:${spring.application.name}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        file-extension: yaml

dubbo:
  application:
    name: settlement-service
  protocol:
    name: dubbo
    port: 20892
  registry:
    address: nacos://${NACOS_SERVER:127.0.0.1:8848}
