server:
  port: 9012

spring:
  application:
    name: settlement-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB_SETTLEMENT:bk_settlement}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: settlement-service
  protocol:
    name: dubbo
    port: 20892
  registry:
    address: nacos://${NACOS_SERVER:127.0.0.1:8848}

management:
  endpoints:
    web:
      exposure:
        include: health,info

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
