server:
  port: 9008

spring:
  application:
    name: marketing-content-service
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false
    nacos:
      discovery:
        enabled: false
      config:
        import-check:
          enabled: false
---
spring:
  config:
    activate:
      on-profile: "!local"
    import: optional:nacos:${spring.application.name}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    discovery:
      enabled: true
    service-registry:
      auto-registration:
        enabled: true
    nacos:
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        file-extension: yaml

dubbo:
  application:
    name: marketing-content-service
  protocol:
    name: dubbo
    port: 20888
  registry:
    address: nacos://${NACOS_SERVER:127.0.0.1:8848}
